# Generated by Django 4.1.5 on 2023-01-29 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='peoople',
        ),
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
