# Generated by Django 4.1.5 on 2023-01-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0003_alter_booking_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_comments',
        ),
    ]
