# Generated by Django 4.1.5 on 2023-01-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0004_remove_booking_additional_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_comments',
            field=models.TextField(default=1, max_length=3000),
        ),
    ]
