# Generated by Django 4.1.5 on 2023-01-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingAPI', '0005_booking_additional_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_comments',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
